modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/PTOM76/solomonsrod-fabric/issues"
license = "MIT"

[[mods]]
modId = "solomons_rod"
version = "${version}"
displayName = "Solomons Rod"
authors = "Pitan, Sayo"
description = '''
This is add Solomons Rod
'''
#logoFile = ""

[[dependencies.solomons_rod]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.solomons_rod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
